### PR TITLE
Getting project to build as of 10/18/2017

### PR DESCRIPTION
**Pull request by MrCsabaToth**

### CODE REVIEW

**Comment by AlexeyBuzdin** [comment]
Thanks Csaba! Have you run an event with the material, how did it went?

**Comment by MrCsabaToth** [comment]
@AlexeyBuzdin Event is coming up this weekend. I see the companion presentation and exercises, I won't use that. I'm exploring the possibility of using the app to give a chance for participants to place their avatars onto our website (GDG-x Hoverboard v2 https://github.com/gdgfresno/valleydevfest2017). First I'll spin out a web based editor (which would use the body parts of this Android app), but also possibly having an Android app (which wouldn't have the audio capability, but would upload the avatar onto the site's Firebase DB).

**Comment by MrCsabaToth** [comment]
Kinda v0/basic version of what 2016 Google I/O + androidify.com had, that was the original goal

**Comment by MrCsabaToth** [comment]
Off topic but I see https://rigadevdays.lv/ uses Hoverboard v2 as well if I'm not mistaken. I have some iOS specific problems, like the hero background photo doesn't appear on iOS supposedly (I don't have devices), only the background drop color (https://github.com/gdgfresno/valleydevfest2017/issues/27). Did you have that problem? I'm interested in any iOS or specific errors you fixed. These are other bugs I may not have time to fix: https://github.com/gdgfresno/valleydevfest2017/issues/35 https://github.com/gdgfresno/valleydevfest2017/issues/38. My site has detailed session rating worth to check BTW. And now it'll have the participants page where people can place their avatars.

**Comment by MrCsabaToth** [comment]
Wow, I'm amazed at Riga Dev Day, I like that it's agnostic and JUG and .NET is involved as well.

**Comment by AlexeyBuzdin** [comment]
@MrCsabaToth thanks for the kind words about Riga Dev Days :) 
Regarding Hoverboard v2 issues, I think we have them as well. We just recently migrated from v1 to v2. Maybe @echoAlexey can tell more. But imho the best way would be to ask Oleh Zasadnyy in the Hoverboard github.

Also, we've developed a completely native Hoverboard compatible apps for iOS and Android, please take a look :) https://github.com/RigaDevDay/RigaDevDays-Swift and https://github.com/siga111/rdd-android Maybe you would be interested in using them for you DevFest

**Comment by MrCsabaToth** [comment]
I saw them in the repo, didn't have time to examine. Are they pulling data from the Firebase DB? If yes they could be migrated to GDG-x (I'm not a GDG-x guy though. I went to both GDG-x talks at the GDG summit this year and several person were interested in native apps. I'm afraid they don't know about these apps)

**Comment by AlexeyBuzdin** [comment]
Yeap, they use the same Firebase Data. Regarding GDG-X, we're in talk with them for quite a while now. They asked to do some additional documentation and we just don't have time for that at the moment. Likely we will be able to do it somewhere next year

**Comment by MrCsabaToth** [comment]
I feel bad because I expressed intention to help their project, but in the end all my time goes to just form the site to our needs. I had some PRs back, but not features like the rating. I wish they had more help, I like them a lot.

**Comment by MrCsabaToth** [comment]
FYI, my edition of the app (https://play.google.com/store/apps/details?id=com.valleydevfest.androidify) is connecting to Firebase and participants can upload their avatars to the website https://valleydevfest.com (see under the Androidify menu). This gives me a great joy!

(By upload to Firebase I mean that Firebase DB stores the three indexes of the body part choices and the name.)

**Comment by AlexeyBuzdin** [comment]
Congrats! I've tweeted a about it from our account to give some exposure :)

**Comment by MrCsabaToth** [comment]
Thanks!

**Comment by MrCsabaToth** [comment]
Now I'm thinking of enhancing the app for the WTM spring season by having more head/body/leg choices and having more extra choices like separately selecting facial hair, props, shoes, etc. Where did you get the artwork from?

**Comment by AlexeyBuzdin** [comment]
Took screenshots from here... https://play.google.com/store/apps/details?id=com.google.android.apps.androidify&hl=en

**Comment by MrCsabaToth** [comment]
I see. Can this violate any licensing? I tried to contact Larva Labs in two different ways before I picked up your app but there was no response.

**Comment by AlexeyBuzdin** [comment]
Hi, to tell the trust I don't know. Since It was for educating purposes in GDG program I was willing to risk

**Comment by MrCsabaToth** [comment]
No worries, thanks for the info. So maybe in the future we need to have our own design.

**Pull request merged**
